#!/bin/bash

set -euo pipefail

# remove the metadata line below if there is no metadata 

nextflow run main.nf \
  -entry afterQC \
  --SAMPLEFILE /path/to/sample/file \
  --postqc_path /path/to/postqc/objects \
  --scrublet_path /path/to/scrublet/outputs \
  --metadata /path/to/metadata/file \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -resume