#!/bin/bash

set -euo pipefail

nextflow run cellgeni/nf-scautoqc -r main \
  -entry only_qc \
  --SAMPLEFILE /path/to/sample/file \
  --ss_prefix /path/to/starsolo-results \
  --cb_prefix /path/to/cellbender-results \
  --ss_out Gene \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -resume