#!/bin/bash

set -euo pipefail

samplefile=/path/to/sample/file
metadatafile=/path/to/metadata/file # comment out this line and remove the corresponding line below if there is no metadata 
postqcpath=/path/to/postqc/objects
scrubletpath=/path/to/scrublet/outputs


[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

nextflow run main.nf \
  -entry afterQC \
  --SAMPLEFILE $samplefile \
  --postqc_path $postqcpath \
  --scrublet_path $scrubletpath \
  --metadata $metadatafile \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -resume