#!/bin/bash

set -euo pipefail

export LSB_DEFAULT_USERGROUP=YourGroup

# remove the metadata line below if there is no metadata 

nextflow run cellgeni/nf-scautoqc -r main \
  -entry after_qc \
  --SAMPLEFILE /path/to/sample/file \
  --postqc_path /path/to/postqc/objects \
  --scrublet_path /path/to/scrublet/outputs \
  --metadata /path/to/metadata/file \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -latest \
  -resume