#!/bin/bash

set -euo pipefail

# remove the metadata line below if there is no metadata 

nextflow run cellgeni/nf-scautoqc -r main \
  -entry only_integrate \
  --path_for_scvi /path/to/object/to/integrate \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -resume