#!/bin/bash

set -euo pipefail

export LSB_DEFAULT_USERGROUP=YourGroup

nextflow run cellgeni/nf-scautoqc -r main \
  -entry only_qc \
  --SAMPLEFILE /path/to/sample/file \
  --ss_prefix /path/to/starsolo-results \
  --cb_prefix /path/to/cellbender-results \
  --qc_mode original \
  --cell_or_nuclei cell \
  --cellbender_input cellbender_out_filtered.h5 \
  --celltypist gut \
  --ss_out Gene \
  --project_tag project1 \
  --batch_key sampleID \
  --ansi-log false \
  -latest \
  -resume